# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ApplicationUser',
            },
        ),
        migrations.CreateModel(
            name='MessageHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('message', models.TextField(max_length=1000)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='WebCrawler.ApplicationUser', to_field='user_id')),
            ],
            options={
                'db_table': 'MessageHolder',
            },
        ),
    ]
