# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCrawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='type',
        ),
        migrations.AddField(
            model_name='messageholder',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 17, 26, 57, 439224)),
        ),
        migrations.AlterField(
            model_name='messageholder',
            name='message_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
