# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCrawler', '0002_auto_20170409_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageholder',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 11, 44, 18, 222646)),
        ),
    ]
