# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCrawler', '0002_auto_20170409_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageholder',
            name='message_update_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
