# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCrawler', '0004_auto_20170409_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='type',
        ),
    ]
